spring.application.name=weechat-backend

spring.mongodb.host=localhost
spring.mongodb.port=21345
spring.mongodb.authentication-database=admin
spring.mongodb.username=weechat_root
spring.mongodb.password=weechat_password
spring.mongodb.database=weechat

spring.datasource.url=jdbc:postgresql://localhost:54321/weechat_db
spring.datasource.username=weechat_user
spring.datasource.password=weechat_password
