spring.application.name=weechat-backend

spring.mongodb.host=localhost
spring.mongodb.port=21345
spring.mongodb.authentication-database=admin
spring.mongodb.username=weechat_root
spring.mongodb.password=weechat_password
spring.mongodb.database=weechat
spring.mongodb.uuid-representation=standard

spring.datasource.url=jdbc:postgresql://localhost:54321/weechat_db
spring.datasource.username=weechat_user
spring.datasource.password=weechat_password

spring.flyway.baseline-on-migrate=true

security.jwt.secret=change-me
security.jwt.access-expiration-seconds=300
security.jwt.refresh-expiration-seconds=2592000
